### PR TITLE
The *.mo translation files have been recompiled

### LINKED ISSUE #5: UnicodeDecodeErrors when loading message catalogs in Python 3.6
I am getting UnicodeDecodeErrors in Python 3.6 when trying to load the Polish and Turkish message catalogs included in the 4.0.0 release of zope.app.locales:

```
>>> gettext.GNUTranslations(open('pl/LC_MESSAGES/zope.mo', 'rb'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/gettext.py", line 254, in __init__
    self._parse(fp)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/gettext.py", line 413, in _parse
    catalog[str(msg, charset)] = str(tmsg, charset)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 15: ordinal not in range(128)
>>> gettext.GNUTranslations(open('tr/LC_MESSAGES/zope.mo', 'rb'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/gettext.py", line 254, in __init__
    self._parse(fp)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/gettext.py", line 413, in _parse
    catalog[str(msg, charset)] = str(tmsg, charset)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 9: ordinal not in range(128)
```

The other message catalogs load successfully.

### PR DESCRIPTION
**Pull request by ale-rt**
Closes #5

### CODE REVIEW

**Comment by mgedmin** [comment]
This breaks tests?  How come this breaks tests?

(Also I'm not very happy with compilation artefacts being committed in the repo, and I would like some reassurances that the binary `.mo` format is platform-independent.)

**Comment by vincentfretin** [comment]
The mo files should be removed from the repo, and only included in the releases (with zest.releaser+zest.pocompile) like I do with plone.app.locales.

**Comment by mgedmin** [comment]
Is there a way to make zest.releaser do that automatically, and most importantly abort if zest.pocompile is not available?  Because if I ever need to make a release, I will run `fullrelease` without remembering any special requirements of any specific package.

**Comment by mauritsvanrees** [comment]
Theoretically, you could add `zest.pocompile` to some `extras_require` in `setup.py`, but that does not install it in the same place where you have already installed `zest.releaser`.

A future option might be to have something in `setup.cfg` like this:

```
[zest.releaser]
requires = zest.pocompile
```

Then `zest.releaser` could try to import `zest.pocompile` and abort if that doesn't work. But that is just an idea.

No way comes to mind that currently works, except installing `zest.pocompile` in the same `virtualenv` (or similar) where you have `zest.releaser`. That is what I have, and it should be fine for all projects. (I guess there can be exceptions.)

**Comment by mgedmin** [comment]
For safety reasons we could add a check in `setup.py` that looks at the timestamps of `*.mo` and aborts if they're older than the timestamps of `*.po`.  I think it would make sense to do that check only when `__version__` does not contain `dev`.  Also, we'd have to remove the `*.mo` from Git so `git checkout` wouldn't accidentally set new timestamps on old `*.mo` files.

**Comment by ale-rt** [comment]
I fixed the build by removing fuzzy in the tr and pl po files are rerunning pocompile.
I would definitely ask some Polish and Turkish people to have a look at the status of their translation files.

I am also +1 to remove the *.mo files from the repo, but this PR is focused on fixing the state of the art of the package and I opened #7 to discuss that.

**Comment by mauritsvanrees** [comment]
> zope_i18n_allowed_languages=de,en,es,fr
> zope_i18n_compile_mo_files=True

I do this too in all my Plone projects. But when you build the site as one user and run it as a different user with less permissions, that user may not have permission to write the `.mo` files, so you could get an error on startup, or you simply miss translations, also when you don't have those lines in your config. So it is always nice to include the `.mo` files in the distribution. (But indeed preferably not in source control.)

**Comment by icemac** [comment]
@ale-rt Feel free to merge. I can create a release afterwards.

**Comment by icemac** [comment]
I just released https://pypi.org/project/zope.app.locales/4.0.1/.

**Pull request merged**
